# --- 1. NETWORK & SECURITY ---
bind 0.0.0.0
# Port sẽ được map từ docker, trong container cứ để mặc định hoặc theo biến cmd
port 6379
protected-mode yes

# --- 2. MEMORY MANAGEMENT ---
# Giới hạn RAM (Có thể override bằng lệnh nếu muốn, nhưng để đây cũng ổn)
maxmemory 512mb
maxmemory-policy allkeys-lru

# --- 3. PERSISTENCE (AOF - An toàn dữ liệu) ---
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec

# --- 4. RDB (Snapshot Backup) ---
save 900 1
save 300 10
save 60 10000

# --- 5. PERFORMANCE ---
maxclients 10000
tcp-keepalive 300