version: '3.8'

services:
  redis:
    image: redis:${REDIS_VERSION:-7.2-alpine} # Lấy version từ .env
    container_name: tripjoy-redis
    restart: always

    # Redis Conf không tự đọc biến môi trường.
    # Ta dùng dòng lệnh này để load config file NHƯNG ghi đè mật khẩu bằng biến env.
    command: >
      redis-server /usr/local/etc/redis/redis.conf
      --requirepass ${REDIS_PASSWORD}
      --port ${REDIS_PORT}

    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data

    networks:
      - tripjoy-network

    sysctls:
      - net.core.somaxconn=1024

networks:
  tripjoy-network:
    driver: bridge

# docker-compose up -d
# docker exec -it tripjoy-redis redis-cli -a TripJoySecurePass2025 ping