spring:
  config:
    activate:
      on-profile: prod

  # Trên prod, Database thường khác URL, nhưng ta đã xử lý bằng Env Var ở file gốc rồi.
  # Ở đây chỉ set các cờ hiệu năng.
  jpa:
    hibernate:
      ddl-auto: validate # Chỉ kiểm tra schema, tuyệt đối không được 'create' hay 'update'

logging:
  level:
    root: WARN # Chỉ log lỗi, giảm rác log
    org.hibernate.SQL: OFF # Tắt log SQL để tăng tốc độ