server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: tripjoy-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    # URL được xây dựng động hoàn toàn
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 1  # Cache layer uses DB 1, Socket.IO uses DB 0

socket-server:
  host: ${SOCKET_HOST}
  port: ${SOCKET_PORT}

jwt:
  signer-key: ${JWT_SIGNER_KEY}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

api:
  swagger:
    info:
      title: Tripjoy API
      version: v1.0.0
    servers:
      dev:
        url: ${SWAGGER_SERVER_URL}
        description: ${SWAGGER_SERVER_DESCRIPTION}