spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG        # Xem câu query
    org.hibernate.type: TRACE       # Xem tham số binding (? trong sql)