/**
 * TripJoy k6 — Data Generators
 *
 * Realistic test data generators for all domain entities.
 * Deterministic per VU iteration for reproducibility.
 */

import { uuidv4 } from 'https://jslib.k6.io/k6-utils/1.4.0/index.js';

// ──────────────────────────────────────────────────────────────
// Primitive helpers
// ──────────────────────────────────────────────────────────────

function pick(arr) {
    return arr[Math.floor(Math.random() * arr.length)];
}

function randInt(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
}

function randStr(len = 8) {
    const chars = 'abcdefghijklmnopqrstuvwxyz0123456789';
    let s = '';
    for (let i = 0; i < len; i++) s += chars[Math.floor(Math.random() * chars.length)];
    return s;
}

// ──────────────────────────────────────────────────────────────
// User
// ──────────────────────────────────────────────────────────────

const ADJ = ['swift', 'brave', 'clever', 'happy', 'lucky', 'mighty', 'wise', 'cool'];
const NOUNS = ['traveler', 'explorer', 'wanderer', 'nomad', 'adventurer'];

export function generateUsername() {
    return `${pick(ADJ)}_${pick(NOUNS)}_${randInt(100, 9999)}`;
}

export function generateEmail(username = null) {
    const user = username || `user_${randStr(8)}`;
    return `${user}_${randStr(4)}@testmail.tripjoy.io`;
}

export function generateUser() {
    const username = generateUsername();
    return {
        username,
        email: generateEmail(username),
        password: 'Test123!@#',
        full_name: `Test ${username.split('_')[0]} User`,
    };
}

// ──────────────────────────────────────────────────────────────
// Group
// ──────────────────────────────────────────────────────────────

const DESTINATIONS = ['Bali', 'Tokyo', 'Paris', 'New York', 'London', 'Rome', 'Seoul', 'Bangkok', 'Da Nang', 'Hoi An'];
const SEASONS = ['Spring', 'Summer', 'Autumn', 'Winter'];

export function generateGroupName() {
    return `${pick(DESTINATIONS)} ${pick(SEASONS)} ${randInt(2024, 2026)} Trip`;
}

export function generateGroupPayload() {
    return {
        name: generateGroupName(),
        description: `k6 test group created at ${new Date().toISOString()}`,
    };
}

// ──────────────────────────────────────────────────────────────
// Post
// ──────────────────────────────────────────────────────────────

const HASHTAGS = ['dulich', 'travel', 'vietnam', 'adventure', 'food', 'culture'];
const POST_CONTENTS = [
    'Chuyen di Da Nang that tuyet voi! Bien xanh cat trang',
    'Kham pha Hoi An co kinh, den long thap sang dem thu.',
    'Foodie trip to Hanoi — bun cha, pho, banh mi. Heaven!',
    'Trekking Sapa highlands — breathtaking views above the clouds.',
    'Ha Long Bay cruise was absolutely stunning. Must-visit!',
];

export function generatePostPayload(itineraryId = null) {
    return {
        content: pick(POST_CONTENTS),
        hashtags: [pick(HASHTAGS), pick(HASHTAGS)].filter((v, i, a) => a.indexOf(v) === i),
        media_urls: [],
        itinerary_id: itineraryId || null,
        visibility: 'PUBLIC'
    };
}

// ──────────────────────────────────────────────────────────────
// Comment
// ──────────────────────────────────────────────────────────────

const COMMENTS = [
    'Tuyet voi qua! Cho minh hoi chi phi bao nhieu a?',
    'Dep qua! Minh cung muon di cho nay.',
    'Cam on ban da chia se, rat huu ich!',
    'That an tuong! Ban di vao mua nao vay?',
    'Great post! Adding this to my bucket list',
];

export function generateCommentPayload(postId) {
    return { post_id: postId, content: pick(COMMENTS) };
}

// ──────────────────────────────────────────────────────────────
// Itinerary
// ──────────────────────────────────────────────────────────────

export function generateItineraryPayload(groupId) {
    const start = new Date();
    start.setDate(start.getDate() + randInt(7, 30));
    const end = new Date(start);
    end.setDate(end.getDate() + randInt(3, 10));

    // Format as LocalDateTime: YYYY-MM-DDTHH:mm:ss
    const formatDT = (date) => date.toISOString().split('.')[0];

    return {
        group_id: groupId,
        name: `${pick(DESTINATIONS)} Adventure ${randInt(1, 99)}`,
        description: 'Auto-generated by k6 load test',
        start_date: formatDT(start),
        end_date: formatDT(end),
        people_quantity: randInt(1, 6),
        budget_estimate: randInt(5000000, 30000000),
    };
}

// ──────────────────────────────────────────────────────────────
// Location / Expense
// ──────────────────────────────────────────────────────────────

const CITIES_VN = [
    { city: 'Ho Chi Minh City', lat: 10.8231, lng: 106.6297, country: 'VN' },
    { city: 'Hanoi', lat: 21.0285, lng: 105.8542, country: 'VN' },
    { city: 'Da Nang', lat: 16.0544, lng: 108.2022, country: 'VN' },
    { city: 'Hoi An', lat: 15.8801, lng: 108.3380, country: 'VN' },
    { city: 'Nha Trang', lat: 12.2388, lng: 109.1967, country: 'VN' },
];

export function randomCity() {
    return pick(CITIES_VN);
}

const EXPENSE_CATEGORIES = ['FOOD', 'ACCOMMODATION', 'TRANSPORT', 'ACTIVITY', 'SHOPPING', 'OTHER'];

export function generateExpensePayload() {
    return {
        name: `Test expense ${randStr(6)}`,
        amount: randInt(50000, 2000000),
        type: pick(EXPENSE_CATEGORIES),
        description: 'k6 test expense',
        method: 'CASH'
    };
}

// ──────────────────────────────────────────────────────────────
// Chat message
// ──────────────────────────────────────────────────────────────

const MSG_TEXTS = [
    'Moi nguoi oi, chung ta di dau truoc nhi?',
    'Minh suggest Hoi An truoc, rat dep!',
    'Ok team, thong nhat lich trinh di!',
    'Ai book khach san chua?',
    'Minh da tim duoc deal tot roi',
    'Countdown: 7 ngay nua len duong!',
];

export function generateMessagePayload() {
    return { message_content: pick(MSG_TEXTS), message_type: 'TEXT' };
}

// ──────────────────────────────────────────────────────────────
// Location suggestion (for groups)
// ──────────────────────────────────────────────────────────────

export function generateSuggestionPayload(locationId) {
    return {
        location_id: locationId,
        notes: `Suggest này từ k6 test — ${randStr(6)}`,
    };
}

export default {
    generateUser,
    generateGroupPayload,
    generatePostPayload,
    generateCommentPayload,
    generateItineraryPayload,
    generateExpensePayload,
    generateMessagePayload,
    generateSuggestionPayload,
    randomCity,
};
