package com.tripjoy.api.enums;

public enum ActivityAction {
    // POST ACTIONS
    POST_CREATED,
    POST_UPDATED,
    POST_DELETED,
    POST_LIKED,
    POST_UNLIKED,
    POST_SAVED,
    POST_UNSAVED,
    POST_SHARED,

    // COMMENT ACTIONS
    COMMENT_CREATED,
    COMMENT_UPDATED,
    COMMENT_DELETED,
    COMMENT_LIKED,
    COMMENT_UNLIKED,
    COMMENT_REPLIED,

    // GROUP ACTIONS
    GROUP_CREATED,
    GROUP_UPDATED,
    GROUP_DELETED,
    GROUP_JOINED,
    GROUP_LEFT,
    GROUP_MEMBER_ADDED,
    GROUP_MEMBER_REMOVED,
    GROUP_ROLE_CHANGED,

    // NOTIFICATION ACTIONS
    NOTIFICATION_CREATED,
    NOTIFICATION_SENT,
    NOTIFICATION_READ,
    NOTIFICATION_DELETED,

    // ITINERARY ACTIONS
    ITINERARY_CREATED,
    ITINERARY_UPDATED,
    ITINERARY_DELETED,
    ITINERARY_SHARED,
    ITINERARY_LIKED,

    // CHAT ACTIONS
    MESSAGE_SENT,
    MESSAGE_DELETED,
    MESSAGE_LIKED,

    // USER ACTIONS
    USER_LOGIN,
    USER_LOGOUT,
    USER_REGISTERED,
    USER_PROFILE_UPDATED
}
